name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 7 with PHP 7.4 (most stable combination for Laravel 7)
          - php: 7.4
            laravel: 7.*
            testbench: 5.*

          # Laravel 8 with PHP 7.4 and 8.0
          - php: 7.4
            laravel: 8.*
            testbench: 6.*
          - php: 8.0
            laravel: 8.*
            testbench: 6.*

          # Laravel 9 with PHP 8.0 and 8.1
          - php: 8.0
            laravel: 9.*
            testbench: 7.*
          - php: 8.1
            laravel: 9.*
            testbench: 7.*

          # Laravel 10 with PHP 8.1 and 8.2
          - php: 8.1
            laravel: 10.*
            testbench: 8.*
          - php: 8.2
            laravel: 10.*
            testbench: 8.*

          # Laravel 11 with PHP 8.2 (Laravel 11 requires PHP 8.2+)
          - php: 8.2
            laravel: 11.*
            testbench: 9.*

          # Laravel 12 with PHP 8.2 (Laravel 12 requires PHP 8.2+)
          - php: 8.2
            laravel: ^12.3
            testbench: ^10.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-update --no-interaction
          composer require "illuminate/database:${{ matrix.laravel }}" --no-update --no-interaction
          composer require "illuminate/support:${{ matrix.laravel }}" --no-update --no-interaction
          composer require "orchestra/testbench:${{ matrix.testbench }}" --no-update --no-interaction --dev
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
